### ISSUE TITLE
Windows expat prefix bug

### ISSUE THREAD

**Issue by Objexx** [modelon-community/fmi-library#29]
In FMIL 2.4.1 Config.cmake/fmixml.cmake line 210 is:
```
"${CMAKE_BINARY_DIR}/ExpatEx/install/lib/${CMAKE_STATIC_LIBRARY_PREFIX}expat${CMAKE_STATIC_LIBRARY_SUFFIX}"
```
but I believe it should be:
```
"${CMAKE_BINARY_DIR}/ExpatEx/install/lib/${EXPAT_LIB_PREFIX}expat${CMAKE_STATIC_LIBRARY_SUFFIX}"
```
Without this fix on Windows the make install looks for expat.lib instead of libexpat.lib and fails.

**Comment by modelonrobinandersson** [comment]
Hi @Objexx! 
Sorry for the late reply, this seems to have changed since you reported it, see https://github.com/modelon-community/fmi-library/blob/9c6a934370875313710e764a4334cfa04dde2342/Config.cmake/fmixml.cmake#L240.

I will close this for now but if you still encounter any issues let me know and I will reopen this.
